/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KURVqlgsA7e
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"

export function Rpg() {
  const [messages, setMessages] = useState([
    {
      id: 1,
      sender: "Player",
      content: "Greetings, adventurer! I need your help to slay the dragon that terrorizes our village.",
      timestamp: "2023-04-01 10:30:00",
      icon: "🗡️",
    },
    {
      id: 2,
      sender: "Wizard",
      content: "I sense a great evil in the mountains. I will lend you my magic to aid in your quest.",
      timestamp: "2023-04-01 10:31:00",
      icon: "🧙‍♂️",
    },
    {
      id: 3,
      sender: "Player",
      content: "Thank you, wise one. I shall gather my courage and set out at once.",
      timestamp: "2023-04-01 10:32:00",
      icon: "🗡️",
    },
  ])
  const [resources, setResources] = useState({
    gold: 100,
    wood: 50,
    stone: 25,
  })
  const [inputValue, setInputValue] = useState("")
  const handleSendMessage = () => {
    if (inputValue.trim() !== "") {
      const newMessage = {
        id: messages.length + 1,
        sender: "Player",
        content: inputValue,
        timestamp: new Date().toLocaleString(),
        icon: "🗡️",
      }
      setMessages([...messages, newMessage])
      setInputValue("")
    }
  }
  return (
    <div className="flex flex-col h-screen bg-[#1e1e1e] text-white">
      <header className="bg-[#2d2d2d] p-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="bg-[#55efc4] rounded-full w-8 h-8 flex items-center justify-center text-2xl">🏰</div>
          <h1 className="text-xl font-bold">RPG Chat</h1>
        </div>
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <div className="bg-[#ffeaa7] rounded-full w-6 h-6 flex items-center justify-center text-lg">💰</div>
            <span>{resources.gold}</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="bg-[#fdcb6e] rounded-full w-6 h-6 flex items-center justify-center text-lg">🌳</div>
            <span>{resources.wood}</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="bg-[#a29bfe] rounded-full w-6 h-6 flex items-center justify-center text-lg">🗿</div>
            <span>{resources.stone}</span>
          </div>
        </div>
      </header>
      <div className="flex-1 overflow-y-auto p-4">
        {messages.map((message) => (
          <div
            key={message.id}
            className={`flex items-start gap-4 mb-4 ${message.sender === "Player" ? "justify-end" : "justify-start"}`}
          >
            <div
              className={`rounded-lg w-10 h-10 flex items-center justify-center text-2xl ${
                message.sender === "Player" ? "bg-[#55efc4]" : "bg-[#fdcb6e]"
              }`}
            >
              {message.icon}
            </div>
            <div className="grid gap-1 items-start text-sm">
              <div className="flex items-center gap-2">
                <div className="font-bold">{message.sender}</div>
                <div className="text-sm text-[#b2bec3]">{message.timestamp}</div>
              </div>
              <div>
                <p>{message.content}</p>
              </div>
            </div>
          </div>
        ))}
      </div>
      <div className="bg-[#2d2d2d] p-4 flex items-center gap-4">
        <input
          type="text"
          placeholder="Type your message..."
          className="flex-1 bg-[#3d3d3d] border-[#4b4b4b] border rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-[#55efc4]"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
        />
        <button
          className="bg-[#55efc4] text-[#1e1e1e] rounded-lg px-4 py-2 font-bold hover:bg-[#48d16a] focus:outline-none focus:ring-2 focus:ring-[#55efc4]"
          onClick={handleSendMessage}
        >
          Send
        </button>
      </div>
    </div>
  )
}
